#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox"
STYLE="dprmd"
RASI=""

# Theme Elements
status="`mpc status`"
if [[ -z "$status" ]]; then
  RASI="$DIR/themes/$STYLE/rofi/music-1.rasi"
	prompt='Offline'
	mesg="MPD is Offline"
else
  RASI="$DIR/themes/$STYLE/rofi/music-7.rasi"
	prompt="`mpc -f "%artist%" current`"
	mesg="`mpc -f "%title%" current` :: `mpc status | grep "#" | awk '{print $3}'`"
fi

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
		if [[ -z "$status" ]]; then
			option_1="󰝚 Turn on MPD"
		else
			option_1="󰝚 Open ncmpcpp"
			if [[ ${status} == *"[playing]"* ]]; then
				option_2=" Pause"
			else
				option_2=" Play"
			fi
			option_3=" Stop"
			option_4=" Previous"
			option_5=" Next"
			option_6=" Repeat"
			option_7=" Random"
	fi
fi

# Toggle Actions
active=''
urgent=''
# Repeat
if [[ ${status} == *"repeat: on"* ]]; then
    active="-a 5"
elif [[ ${status} == *"repeat: off"* ]]; then
    urgent="-u 5"
else
    option_6=" Parsing Error"
fi
# Random
if [[ ${status} == *"random: on"* ]]; then
    [ -n "$active" ] && active+=",6" || active="-a 6"
elif [[ ${status} == *"random: off"* ]]; then
    [ -n "$urgent" ] && urgent+=",6" || urgent="-u 6"
else
    option_7=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	if [[ -z "$status" ]]; then
		echo -e "$option_1" | rofi_cmd
	else
		echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6\n$option_7" | rofi_cmd
	fi
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		if [[ -z "$status" ]]; then
			mpd &
		else
			alacritty -e ncmpcpp
		fi
	elif [[ "$1" == '--opt2' ]]; then
		mpc -q toggle && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt3' ]]; then
		mpc -q stop
	elif [[ "$1" == '--opt4' ]]; then
		mpc -q prev && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt5' ]]; then
		mpc -q next && kunst --size 60x60 --silent
	elif [[ "$1" == '--opt6' ]]; then
		mpc -q repeat
	elif [[ "$1" == '--opt7' ]]; then
		mpc -q random
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
    $option_7)
		run_cmd --opt7
        ;;
esac
